### PR TITLE
Parse Bluetooth vendor IDs

### LINKED ISSUE #783: Incorrect manufacturer detected for Bluetooth Apple Magic Keyboard
I have a Bluetooth Magic Keyboard, full size. `bluetoothDevices()` gives me the following:

```javascript
[
  {
    device: '0x800020 < HID ACL >',
    name: 'FirstName LastName’s Keyboard',
    manufacturer: 'FirstName',
    macDevice: 'd4:dc:cd:83:d2:XX',
    macHost: '3c:06:30:3f:24:YY',
    batteryPercent: null,
    type: 'Keyboard',
    connected: true
  }
]
```

When I run `system_profiler SPBluetoothDataType -json`, I get:

```json
{
  "SPBluetoothDataType" : [
    {
      "controller_properties" : {
        "controller_address" : "3C:06:30:3F:24:YY",
        "controller_chipset" : "BCM_4378",
        "controller_discoverable" : "attrib_off",
        "controller_firmwareVersion" : "20.1.500.3160",
        "controller_productID" : "0x4A01",
        "controller_state" : "attrib_on",
        "controller_supportedServices" : "0x382039 < HFP AVRCP A2DP HID Braille AACP GATT SerialPort >",
        "controller_transport" : "PCIe",
        "controller_vendorID" : "0x004C (Apple)"
      },
      "device_connected" : [
        {
          "FirstName LastName’s Keyboard" : {
            "device_address" : "D4:DC:CD:83:D2:XX",
            "device_batteryLevelMain" : "100%",
            "device_firmwareVersion" : "1.6.0",
            "device_minorType" : "Keyboard",
            "device_productID" : "0x026C",
            "device_rssi" : "-55",
            "device_services" : "0x800020 < HID ACL >",
            "device_vendorID" : "0x004C"
          }
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by schontz**
Fixes #783

### CODE REVIEW

**Comment by schontz** [comment]
This still falls back to device_name for manufacturer. I'd suggest we don't use that as fallback because it could accidentally contain PII. For apps that are trying to remove PII when logging, they do not expect PII to be found in a manufacturer field.

**Comment by sebhildebrandt** [comment]
@schontz ... I need to have a closer look. As posted yesterday I also started to work on a fix for that. I also need to test the resulting fix on several machines. Will come back as soon as I have finished it.

**Comment by schontz** [comment]
Sounds good. I only tested on my machine, so this will obviously need a broader test.

**Comment by schontz** [comment]
No apologies necessary. For what it's worth, I've been running with a patched version of this without any issue, so it at least isn't breaking things.

**Comment by sebhildebrandt** [comment]
@schontz yes, but you spend your time on this nice patch!! I really appreciate it!

**Comment by sebhildebrandt** [comment]
@schontz ... sorry for the very long delay ... I now merged your PR and extended the vendor list ... version 5.23.23 just released. Thank you for your contribution!! Happy holidays.

**Pull request merged**
