### PR TITLE
Add windowsHide: true to exec options, don't spawn windows on windows

### PR DESCRIPTION
**Pull request by ItsJimi**
## Pull Request

There is no issue created

#### Changes proposed:

* [x] Fix

#### Description (what is this PR about)

On windows, `exec` create a window when a subprocess is launched.
`windowsHide: true` hide the subprocess console window that would normally be created on Windows systems. 
https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
Hi @ItsJimi 
Thank you for your pull request. One question: from the docs I understand that this option is needed especially on Windows systems. You added this option also to all other OS systems. I personally would only add it for Windows exec calls. Any objections?
(no need to correct your pull request, I will do it here if you agree)

**Comment by ItsJimi** [comment]
Perfect! Thanks :smile:

**Comment by sebhildebrandt** [comment]
Thank you for your contribution! Published changes (for Windows exec only)

**Comment by ItsJimi** [comment]
My first name has only one "m", `Jimi M` :smile:
Thanks

**Comment by sebhildebrandt** [comment]
Oh ... sorry! Corrected but not yet published ... will do it together with upcoming changes ... ;-)

**Pull request closed without merging**
