### PR TITLE
isCharging now uses pmset

### PR DESCRIPTION
**Pull request by VictorLeach96**
#### Changes proposed:

* [x] Fix
* [ ] Add
* [ ] Remove
* [ ] Update

#### Description

If the battery is at 100% but plugged in then isCharging reports false. I don't think this makes sense as it still has a power connection.

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
@VictorLeach96 : yes you are right. Just fixed it (with a little modification to your pull request). New release 3.37.10 published. Thank you!

**Comment by sebhildebrandt** [comment]
Had to correct it one more time ... can you test it on your side? new published version is 3.37.11

**Comment by sebhildebrandt** [comment]
So this means, peseta has the following outputs:

- discharging
- charged
- charging
- AC connected

for the first two `ischarging` is `false`, for the last two it is `true`, right? I implemented it check now that way. OK for you?

**Comment by VictorLeach96** [comment]
With this configuration ischarging is false when the status is charged which is incorrect I think.

I think discharging is the only state where the power adapter would be unplugged.

**Comment by sebhildebrandt** [comment]
OK, then this is a semantic thing ... if `ischarging`means "power adapter plugged" then you are right. But if `ischarging` should represent if the battery is actually is charging then it should be like this:

```
|--------------|------------|
| pmset        | ischarging |
|--------------|------------|
| discharging  | false      |
| charged      | false      |
| charging     | true       |
| AC connected | false      |
|--------------|------------|
```

**Comment by VictorLeach96** [comment]
Yeh I agree it's a semantic thing. Not sure what use cases you'd have for charging itself.

Our use case is we want to check whether the power adapter is plugged in or not.

**Comment by sebhildebrandt** [comment]
Then it would make sense to add another property to indicate this - independent from then `ischanging`. I will add this tomorrow ...

**Comment by VictorLeach96** [comment]
Yes that would be great, thanks a lot!

**Comment by sebhildebrandt** [comment]
Added `battery.acconnected`

Version 3.38.0 published

**Pull request closed without merging**
