### PR TITLE
add nvidia-smi support

### PR DESCRIPTION
**Pull request by mily20001**
Hi, I've added function for obtaining gpu details using nvidia-smi. To work, it requires installation of official Nvidia drivers. Tested on Linux and Windows machine. It's my first PR here, so let me know if something should be done differently.

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
@mily20001 thank you! This is great. There is one general thing, that I am not sure about: there is already a function `si.graphics()` and I would like to see the information there (extending the already existing information). What do you think?

**Comment by mily20001** [comment]
@sebhildebrandt Do you mean to make it part of `controllers` data or add another object next to `controllers` and `displays`? Extending `contollers` should be doable as we can match them by PCI address.

**Comment by sebhildebrandt** [comment]
@mily20001 Exactly. So then it it much easier to get graphics information fron ONE object. As I currently do not have a linux machine with Nvidia Graphics, I cannot really provide it right now. Need to think how I can do it ...

**Comment by mily20001** [comment]
@sebhildebrandt On windows it's not that easy, because `wmic` doesn't return PCIe address of gpus, however it probably could be matched using `pci.sub_device_id` from `nvidia-smi` and `PNPDeviceID` from `wmic`, I can look into that tomorrow. On Linux it's rather straightforward since we have PCIe address in both sources (`lspci` and `nvidia-smi`)

**Comment by mily20001** [comment]
@sebhildebrandt I've added that info to `si.graphics` as we talked, but I also left the separate function just for getting data from nvidia-smi. I think it's a good idea to have it separated for three reasons:
-on linux `lspci` requires sudo, while `nvidia-smi` doesn't, so if you just need info from `nvidia-smi` you can get them without sudo
-data from `nvidia-smi` is dynamic, while most of data from `si.graphics` is static
-`si.graphics` runs quite a lot of commands under hood, to get mostly static data (for example display resolution can change, but it's not changing every second), so if want to monitor your gpu status (which changes often) you will be calling a lot of other commands, which take time and generates overhead, since in most cases output from other commands will be the same each time.

**Comment by biocyberman** [comment]
Interesting. While you are at it, @mily20001: Be sure to include GPU utilization (MEM, compute) information.

**Comment by mily20001** [comment]
@biocyberman is there anything that is missing? Information about gpu and memory utilization are included.

**Comment by biocyberman** [comment]
That's great. I haven't installed and tried the package so I didn't see. Actually want to use that on a server. So, does it have a web interface?

**Comment by sebhildebrandt** [comment]
@mily20001 will try to merge it but I see some issues here that I have to solve.

**Comment by sebhildebrandt** [comment]
@mily20001 , @biocyberman ... as I needed to change some things, and I am not able to test it (no Nvidia here ...), would you have time to test it ... will push my code to GitHub on Wednesday. Just give me a short note, if you are willing to test this.

**Comment by mily20001** [comment]
@sebhildebrandt I can test it :)

**Comment by sebhildebrandt** [comment]
@mily20001 So I adapted your code and modified it ... also due to compatibility problems (node 4 support will not allow spread operators and async / await). As I was coding this "blind" I would be happy, if you cound test this and give feedback if you discover issues:

I pushed the code to github.

You will find your code snippets now all in the lib/graphics.js file:

- line 368-449: your functions nvidiaDevices, getNvidiaSmi, nvidiaDevices
- line 451-469: mergeControllerNvidia (as a replacement for the spread functions)
- line 708-712: here we get the Nvidia data and try to merge it for the linux part
- line 764-775: here we get the Nvidia data and try to merge it for the windows

I currenty did NOT include a separate function to just get the nvidia data (as you supposed).

Thank you for testing and providing feedback

**Comment by sebhildebrandt** [comment]
@mily20001 did you have time to give it a try? I should push another correction and waiting if the nvidis-smi enhancement works ;-) Thank you in advance for a feedback.

**Comment by sebhildebrandt** [comment]
@mily20001 already published.a new version ... not quite clear if the Nvidia-smi support works as expected...

**Comment by seniorquico** [comment]
@sebhildebrandt We had been running a fork of this PR branch in our production app with good success. On my machine, the VRAM originally reported by other methods would be incorrect while `nvidia-smi` would be correct. I just upgraded to version 4.33.1, and now I get the following:

```js
// si.graphics().then(console.log)
{ controllers: [], displays: [] }
```

Unfortunately, I think version 4.33.0/4.33.1 broke our use case. I'm happy to help pitch in with testing. I've got access to a lot of users with different NVIDIA GPUs and driver versions.

**Comment by sebhildebrandt** [comment]
@seniorquico Thank you for this first test. I would highly appreciate if you can post outputs of `nvidia-smi.exe` on windows and `nvidia-smi` on linux machines and post it as text here. Then I can easily mock the output and see what is going wrong. 

Thank you in advance.

**Comment by mily20001** [comment]
@sebhildebrandt sorry, I'm quite busy in that near-christmas time, so I was not able to test it. Here is full command that is used in my commit:
```bash
nvidia-smi --query-gpu=driver_version,pci.sub_device_id,name,pci.bus_id,fan.speed,memory.total,memory.used,memory.free,utilization.gpu,utilization.memory,temperature.gpu,temperature.memory,power.draw,power.limit,clocks.gr,clocks.mem --format=csv,noheader,nounits
```
For linux here is example output:
```
450.57, 0x244519DA, GeForce GTX 1070 Ti, 00000000:01:00.0, 37, 8119, 4856, 3263, 14, 3, 38, N/A, 41.22, 180.00, 1607, 3802
450.57, 0x85F71043, GeForce GT 710, 00000000:04:00.0, [N/A], 981, 871, 110, [N/A], [N/A], 45, N/A, [N/A], [N/A], [N/A], [N/A]
```

**Comment by sebhildebrandt** [comment]
@mily20001 ... no stress. Sorry for "pushing" 

Thank you for providing the first output. Will have a look tomorrow. I am basically using the exact code from your pull request but repositioned it and just changes the merging part ... maybe I did something wrong here.

**Comment by sebhildebrandt** [comment]
@mily20001 @seniorquico I testet some things by mocking the output ... so I can see that some things are working as expected but I cannot test the overall picture. Would it be possible to grab my latest code from GitHub or NPM and modify the lib/graphics.js to output some intermediate data:

I would e.g. add;

- in line 397 ... right at the end of the getNvidiaSmi: `console.log(_nvidiaSmiPath)` ... to see if the command is detected correctly
- in line 406: `console.log(res)` ... to detect if the output of nvidia-smi is here
- in line 430: `console.log(splittedData)` ... to see if it is splitted correctly
- in line 453:` console.log(results)` ... to see if we have a valid object for all Nvidia GPUs
- in line 473: right before the return controller: `console.log(controller)` ... to see if we have a valid object for all Nvidia GPUs

then for linux:
- in line 713 right after `const nvidiaData = nvidiaDevices();`: console.log(nvidiaData)
- in line 715 before the `map`: console.log(result.controllers)
- in line 718 after the `map`: console.log(result.controllers) ... to see if this was merged correctly
If we see a problem here, maybe the FIND function has a problem ... then I would need to see the `result.controllers`before the map as well as the `nvidiaData`

same for windows:
- in line 770 right after `const nvidiaData = nvidiaDevices();`: console.log(nvidiaData)
- in line 777 before the `map`: console.log(result.controllers)
- in line 781 after the `map`: console.log(result.controllers) ... to see if this was merged correctly
If we see a problem here, maybe the FIND function has a problem ... then I would need to see the `result.controllers`before the map as well as the `nvidiaData`

Thank you for your support.

**Comment by emanuelbaran** [comment]
> @sebhildebrandt We had been running a fork of this PR branch in our production app with good success. On my machine, the VRAM originally reported by other methods would be incorrect while `nvidia-smi` would be correct. I just upgraded to version 4.33.1, and now I get the following:
> 
> ```js
> // si.graphics().then(console.log)
> { controllers: [], displays: [] }
> ```
> 
> Unfortunately, I think version 4.33.0/4.33.1 broke our use case. I'm happy to help pitch in with testing. I've got access to a lot of users with different NVIDIA GPUs and driver versions.

[Win10/Nvidia 2070]
I have the same empty `[]` response with `4.33.1`
Not working on `4.33`
`4.32` works :)

**Comment by seniorquico** [comment]
> Would it be possible to grab my latest code from GitHub or NPM and modify the lib/graphics.js to output some intermediate data

I'll be able to do this on my dev machine, but I won't be able to push this out in the production build of our app. However, I've put out a request with our community asking for users to run the `nvidia-smi` query included above. I'll pull together several examples that might appear to be a little different from each other.

**Comment by sebhildebrandt** [comment]
@seniorquico it would be super helpful if you can make some test on your dev machine. I her the feeling that this is maybe just a minor problem that could be fixed quite simple. But as I cannot reproduce it here due to lack of the apropriate hardware I need some help here. If you can add the logging commands I supposed a d report back what your get as output, we then could see where it breaks. Thank you for your support.

**Comment by buffmail** [comment]
I also have a problem after commit 0da06759cbe0b331b0e3fdde4d35ea39bc759493 and did some investigation.

The reason is that following function is supposed to return string, but actually return Buffer object.

```javascript
  function nvidiaSmi(options) {
    const nvidiaSmiExe = getNvidiaSmi();
    if (nvidiaSmiExe) {
      const nvidiaSmiOpts = '--query-gpu=driver_version,pci.sub_device_id,name,pci.bus_id,fan.speed,memory.total,memory.used,memory.free,utilization.gpu,utilization.memory,temperature.gpu,temperature.memory,power.draw,power.limit,clocks.gr,clocks.mem --format=csv,noheader,nounits'
      try {
        const res = execSync(nvidiaSmiExe + ' ' + nvidiaSmiOpts, options);
        return res;
      } catch (e) {
        util.noop();
      }
    }
    return '';
  }
```

The signature of `execSync()` is like
```javascript
    function execSync(command: string, options?: ExecSyncOptionsWithStringEncoding): string;
    function execSync(command: string, options?: ExecSyncOptionsWithBufferEncoding): Buffer;
    function execSync(command: string, options?: ExecSyncOptions): Buffer;
```

In this case, options is undefined, and I guess it's unclear which function should be executed, and my windows machine return Buffer object, and following `const gpus = stdout.split('\n').filter(Boolean);` line causes exception, because stdout is Buffer object.

So if you change like this, it will work :)
```
<         const res = execSync(nvidiaSmiExe + ' ' + nvidiaSmiOpts, options);
---
>         const res = execSync(nvidiaSmiExe + ' ' + nvidiaSmiOpts, options).toString();
```

**Comment by sebhildebrandt** [comment]
@buffmail Thank you!!!! I gies this is the problem. Will provide a fix later tonight.

**Comment by sebhildebrandt** [comment]
@buffmail thank you once again! I hope, this solves the issue now. As I cannot make any tests with Nvidia graphic cards here, It would be nice, if you can test it once again. @mily20001, @seniorquico, @emanuelbaran can you also test the latest version 4.33.2? 

Thank you all for your support! Best regards.

**Comment by emanuelbaran** [comment]
@sebhildebrandt `4.33.2` is giving back the right info on my side 😄  Great job for the quick fix! 
Tested on Windows 10
`{
  controllers: [
    {
      vendor: 'NVIDIA',
      model: 'NVIDIA GeForce RTX 2070 SUPER',
      bus: 'PCI',
      vram: 4095,
      vramDynamic: true,
      subDeviceId: '40011458'
    }
  ],
  displays: [
    {
      vendor: '(Standard monitor types)',
      model: 'Generic PnP Monitor',
      deviceName: '\\\\.\\DISPLAY1',
      main: true,
      builtin: false,
      connection: 'DP',
      resolutionx: 2560,
      resolutiony: 1440,
      sizex: 60,
      sizey: 34,
      pixeldepth: '32',
      currentResX: 2560,
      currentResY: 1440,
      positionX: 0,
      positionY: 0
    },
    {
      vendor: '',
      model: '',
      deviceName: '\\\\.\\DISPLAY2',
      main: false,
      builtin: false,
      connection: 'HDMI',
      resolutionx: 2560,
      resolutiony: 1440,
      sizex: 61,
      sizey: 35,
      pixeldepth: '32',
      currentResX: 2560,
      currentResY: 1440,
      positionX: 2560,
      positionY: 0
    }
  ]
}`

**Comment by buffmail** [comment]
@sebhildebrandt Thank you for your quick fix :)

Now, `{ controllers: [], displays: [] }` result fixed, but following line still have a problem at windows.

```javascript
      const cmd = nvidiaSmiExe + ' ' + nvidiaSmiOpts + _linux ? '  2>/dev/null' : '';
```

The intention is 
```javascript
      const cmd = nvidiaSmiExe + ' ' + nvidiaSmiOpts + (_linux ? ' 2>/dev/null' : '');
```

But the unary plus operator (+) has higher precedence than ternary operator ( ? : ), so it is interpreted like 
```javascript
      const cmd = (nvidiaSmiExe + ' ' + nvidiaSmiOpts + _linux) ? ' 2>dev/null' : ''
```

So `cmd` always have `'>2/dev/null'` value, which makes `execSync()` fail on windows platform. (But no warning because exception is catched and nothing is done. `nvidia-smi` cmd is just always ignored). 

Would you fix it  please?

**Comment by sebhildebrandt** [comment]
@buffmail thank you! My fault ... fixed! Version 4.33.3 just published. Closing this for now.

Thank you all for your support!

**Pull request closed without merging**
