### PR TITLE
filesystem.js: Fix fsStats() linux block devices

### PR DESCRIPTION
**Pull request by sergeysedoy97**
The current implementation of fsStats is not working correctly.

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
@sergeysedoy97 thank you, can you provide output of 

(current code)
```
lsblk 2>/dev/null | grep /
```

and 

(suggestion)
```
lsblk 2>/dev/null -r | grep /
```

where you have incorrect outputs of `fsStats()`?

Thank you in advance.

**Comment by sergeysedoy97** [comment]
> @sergeysedoy97 thank you, can you provide output of
> 
> (current code)
> 
> ```
> lsblk 2>/dev/null | grep /
> ```
> 
> and
> 
> (suggestion)
> 
> ```
> lsblk 2>/dev/null -r | grep /
> ```
> 
> where you have incorrect outputs of `fsStats()`?
> 
> Thank you in advance.

```~$ lsblk 2>/dev/null | grep /
|-sda1   8:1    0  200M  0 part /boot/efi
|-sda2   8:2    0   20G  0 part /
`-sda5   8:5    0 11.8G  0 part /data
~$ lsblk 2>/dev/null -r | grep /
sda1 8:1 0 200M 0 part /boot/efi
sda2 8:2 0 20G 0 part /
sda5 8:5 0 11.8G 0 part /data`

**Comment by sebhildebrandt** [comment]
@sergeysedoy97 thank you so much ... I see an extra character at the beginning of the line. Just curious, which version of util-linux you are using?

```
lsblk --version
```

**Comment by sergeysedoy97** [comment]
> @sergeysedoy97 thank you so much ... I see an extra character at the beginning of the line. Just curious, which version of util-linux you are using?
> 
> ```
> lsblk --version
> ```

```
~$ lsblk --version
lsblk from util-linux 2.32.1
```

**Comment by sebhildebrandt** [comment]
@sergeysedoy97 thank you, will provide the fix soon. Need to test one more thing here locally.

**Comment by sebhildebrandt** [comment]
@sergeysedoy97 fixed along with another issue I just discovered. Version 5.2.7 just published. Thank you!

**Pull request closed without merging**
