### PR TITLE
Mainly added IOPS to fsStats & recursively called ƒ to compute fs and network speeds

### PR DESCRIPTION
**Pull request by Buzut**
Hi!

I found it unusual to have to manually call the function twice to obtain fs and network speeds so I called them recursively in th code (though it's a little bit slower now…). 

I also added IOPS to `fsStats` as I found it to be an important metric. 

Finally, I made some small changes to the code like consistency with `\n` and using a closure to track functions completion. It allows both to start them all in parallel and to avoid callback hell.

Hope you'll find it useful!

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
Hi, 

thank you for your input and your pull request. I would like to check it before merging it to the master. I will do it next week and send you comments, ok?

regards (and once again thank you!)
Sebastian

**Comment by Buzut** [comment]
Hi Sebastian,

Sure not a problem. 

It is me who has to thank you for this really helpfull library!
Also note that I've been able to test IOPS only against Ubuntu 14 & 16.04.

**Comment by sebhildebrandt** [comment]
Hi again,

I am sorry to not responding for a longer time (first very busy, then on holiday). I am currently reviewing all your pull request (THANK you for your contribution!!). Most of the things are pretty clear, but there are three things that I want to mention:

**diskIO stats:** I tried that also on my machines, some of them have an virtual raid and there this does not really work. I have to reinvestigate to get the right numbers.

**calling networkStats, fsStats twice** (to obtain stats in a certain time): I had a good reason implemented it that way. This way, you can define how long you wait, to get stats. Anyway in my use cases, I am calling all dynamic functions in a loop, to get up to date stats (and after the second time, you get it continuously). My suggestion is now: I would rewrite the function like that: 

```
	function fsStats(callback, msTimeout) {
		...
	}
```
and 

```
	networkStats(iface, callback, msTimeout) {
		...
	}
```

... where "msTimeout" is an optional parameter. If this is blank, it behaves the way I am using it, if not, it behaves the way you intended to use it. This way the timeout value is also not hard coded!

**Callbacks (and callback hell)**

I am about to transform all functions a little bit where the callback-parameter is optional. The idea is: if you ommit the callback, then you can use it in an promis oriented way:

```
// callback oriented usage
si.cpu().then(function(data) {
    console.log(data);
})

// promise oriented usage
si.cpu().then(result => console.log(result))
```

I guess will need about 1 week to make it ready and test it ...

**Comment by sebhildebrandt** [comment]
Most of the things now available in version 3.0 except of this setTimeout(3000) in fsStats and networkStats. DisksIO is now a separated function (not part of fsStats). I had to rewrite parts because they did not worked on several of my machines. Anyway THANK YOU for your contributions and ideas! Highly appreciated!

**Pull request closed without merging**
