### PR TITLE
updated to include the first freebsd info via dmidecode

### LINKED ISSUE #99: add freebsd support
### Issue Type

* [ ] Bug
* [x ] Feature Request
* [ ] Question

### Expected behavior 

- using the module I would expect to have some bsd support
- 
- 

### Actual behavior

-  none is found
- 
- 

### Steps to reproduce the problem

- run code on freebsd system
-
-

### Specifications 

- package version: 3.x
- operating system: freebsd
- hardware: x86 x86_64

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ... 

I would recommend using dmidecode for system info instead of lspci for linux.   dmidecode allows for a full system pull from the BMC.

### PR DESCRIPTION
**Pull request by chair300**
## Pull Request

Fixes #99 

#### Changes proposed:

* [ ] Fix
* [ ] Add
* [ ] Remove
* [ x] Update

#### Description (what is this PR about)

Brief explanation of the changes you have made and/or the new content you are contributing.

The change committed will provide a dmidecode interface for capturing cpu info.   This only captures the cpu info from the bmc not the usage or utilization.

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
@chair300 : working hard on FreeBSD implementation ... more work than I thought ;-) 
Hope to get a first version finished end of next week.

**Comment by chair300** [comment]
That's great.   I know freebsd is a bit harder then Linux.   I am still
happy to help since I have been maintaining freebsd boxes for >10 years.
 I have a little experience is all I am trying to say.

**Comment by sebhildebrandt** [comment]
@chair300 ... Will definitely come back to you! Just want to get at least some things working right now ;-)

**Comment by sebhildebrandt** [comment]
@chair300 ... thank you for your patience. 

So, I now implemented first partial FreeBSD support. In this first release I implemented aprox. 70% of all functions (see docs `README.md`).

I had to reimplement nearly every function ;-) And your code helped me to move into the right direction. But for most of the supported functions I only made some basic tests. 

It would be cool, if you can also test them. If you discover issues, please share your discoveries. If possible, please provide also the output of the underlying shell command (which you should find in the code). That would help me improve the implementation

**Pull request closed without merging**
