### PR TITLE
Show DHCP status, 802.1x status, 802.1x protocol , and DNS suffix

### PR DESCRIPTION
**Pull request by juancampuzano**
The following fields were added to the networkInterfaces () method:

DHCP status: validate if adapter is using static or dinamic (DHCP).
DNS-suffix and adapter specific: The device DNS name and The adapter's specific connection DNS suffix.
802.1x Protocol: If device connected to wired or wireless 802.1x. What connection protocol (EAP-TLS/MSCHAPv2, etc.)
802.1x status: If device connected to wired or wireless 802.1x is enable or disabled

### CODE REVIEW

**Comment by ricardopolo** [comment]
@sebhildebrandt this PR is essential in our projects, and I believe it is a perfect addition for System Information. 
Could you please tell us if you had time to check this PR? Is there anything we can improve so you can approve it?

Thanks!!

**Comment by sebhildebrandt** [comment]
@juancampuzano Sorry for not responding that long ... I had no time to review it. I will try to manage to make some internal tests and merge it in the next few days.

**Comment by sebhildebrandt** [comment]
@juancampuzano @ricardopolo merged your pull request but I need to make some modifications to make it also consistent for other platforms (e.g. OS X). Maybe I will also change name of the properties. Then I will also add documentation. Hope to make progress tonight.

**Comment by sebhildebrandt** [comment]
@juancampuzano @ricardopolo ... to make this also consistent with mac OS I would like to get some example output (perhaps with explanation) of the four added properties. One more thing. I changes the names of two of your newly introduces properties of `networkInterfaces()`: The names (and types) are now:

```
    dhcp: boolean;
    dnsSuffix: string;
    ieee8021xAuth: string;
    ieee8021xState: string;
```
Hope that this is OK. Current changes pushed here to GitHub bit still not published new npm package.

**Pull request merged**
