### PR TITLE
fix typo and command injection

### PR DESCRIPTION
**Pull request by Yoshino-s**
I have tested all security problem with may related to the pr https://github.com/418sec/systeminformation/pull/7
And I didn't find any vulnerability about this fix, but just a little typo.

### CODE REVIEW

**Comment by Yoshino-s** [comment]
well, there is still an injection point. :P

Also, I want to talk more about `inetChecksite` and `inetLatency`. No matter how we fix this two function, there always be something more that we can do with `curl` or `ping`, such as `gopher://` or do some SSRF(Server-side request forgery) to attack host in Intranet.

And the detection and defence of ssrf attack or something more shouldn't be this package's issue. Maybe we should alert user DO NOT use this two function with arbitrary untrusted user input.

**Comment by sebhildebrandt** [comment]
@Yoshino-s  made a litte code refactoring yesterday evening and fixed your pull request issues anyway ...

**Comment by sebhildebrandt** [comment]
@Yoshino-s  Extended also schema validation but still, yes not all is in scope of this package. Made some extra remarks in the documentation.

**Comment by Yoshino-s** [comment]
thanks a lot, the fix looks nice and i think we can finish this series of vulnerability. And now can we apply for the CVE Code?

PS. It may be my first CVE. 😄

**Comment by sebhildebrandt** [comment]
So I also can apply for an CVE as I did before … OK for you?

Sebastian Hildebrandt

+innovations
APPLICATION DEVELOPMENT GMBH
Engerthstr. 147/2/35
1020 Wien - Austria
Mobile: +43 699 10414946
***@***.*** ***@***.***>
https://www.plus-innovations.com <https://www.plus-innovations.com/>
HG Wien, FN 378483 v
GF: Sebastian Hildebrandt        t  <https://www.twitter.com/plusinnovations>f <https://www.facebook.com/plusinnovations>

**Comment by Yoshino-s** [comment]
sure, thanks a lot.

**Comment by sebhildebrandt** [comment]
OK, CVE ID requested. Will publish the security advisory as soon as I get the ID

**Pull request closed without merging**
