### PR TITLE
Improved IPv6 address selection

### LINKED ISSUE #74: Not returning correct external IPv6 address
When I run `si.networkInterfaces()` it returns the incorrect IPv6 address for my interface. Instead of reporting the external address, it reports the [link local address](https://www.cisco.com/c/en/us/support/docs/ip/ip-version-6-ipv6/113328-ipv6-lla.html), starting with `fe80::`. 

These addresses should probably be filtered out, so that the proper external IP address can be selected.

### PR DESCRIPTION
**Pull request by adamreisnz**
- Will pick the first IPv6 address from the list instead of the last
- Will prefer external addresses over link local address
- Fixes #74

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
Hi Adam, 
Thank you for pointing to that problem and your pull request. I guess there is just one minor issue here: I the if statement, shouldn't it be `!ip6.match(/^fe80::/i)`(the "not" was missing) ?

**Comment by adamreisnz** [comment]
Cheers, no problem. No, it's actually checking the `ip6` variable (not iface.address), so the logic is:

- If there is no remembered IPv6 address yes, OR 
- if the remembered IPv6 address is a link local address, THEN
- Overwrite the address

**Comment by sebhildebrandt** [comment]
You are absolutely right! Was just a little confused ;-)

**Comment by adamreisnz** [comment]
To be fair, I was too, when I wrote the code ;)

**Comment by sebhildebrandt** [comment]
Just published a new version with this fix (v3.30.2) . Thank you so much!

**Comment by adamreisnz** [comment]
Awesome, thanks!

**Pull request closed without merging**
