### PR TITLE
Added pip, python3, pip3 and java to versions

### PR DESCRIPTION
**Pull request by DerEisvogel**
Hey,

I would love to to see the following packages being added to the version request:
- pip
- python3
- pip3
- java

Please consider my pull request to add the these to the version request.

Thanks.

Best Regards,
Der Eisvogel

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
Hi @DerEisvogel , thank you for your contribution. Will check it this week on all platforms.

**Comment by sebhildebrandt** [comment]
Hi, I added java and python3 along with other optimisations in versions, but had some problems with pip ... will check how to solve this ...

**Comment by DerEisvogel** [comment]
Hey, excellent. Thank you.
What issues did you encounter with `pip`?

**Comment by sebhildebrandt** [comment]
@DerEisvogel : pip problem was actually a corrupt / weird installation of pip on one of my machines ... solved it, not also added pip and pip3 version detection.

**Pull request closed without merging**
