### PR TITLE
Add files to package.json

### PR DESCRIPTION
**Pull request by styfle**
## Pull Request

Fixes npm publish

#### Changes proposed:

* [x] Fix
* [ ] Enhancement
* [ ] Remove
* [ ] Update

#### Description (what is this PR about)

This will avoid publishing [unnecessary files](https://unpkg.com/systeminformation@3.45.6/) to npm, for example `docs/` or `.editorconfig`.

See the [package.json](https://docs.npmjs.com/files/package.json#files) documentation for more info.

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
Added ... and published new version. Thank you

**Comment by styfle** [comment]
Why didn’t you merge this PR?

**Comment by sebhildebrandt** [comment]
I made a couple more changes ...

**Comment by styfle** [comment]
Right, but it gives you credit instead of me because my commit never made it to master.

**Pull request closed without merging**
